print("Welcome to the tip calculator.")
bill = float(input("What was the total bill? $"))
percent = float(input("What percentage tip would you like to give? 10, 12, or 15?"))
numPeople = int(input("How many people to split the bill? "))
result = round((bill * (1 + percent/100))/numPeople, 2)
print("Each person should pay: $", result)